// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd6I24GWidKNeYlVbHAVJjP6ekjvMlPoo',
    appId: '1:431166589438:web:d2801771e8ce8d0b4918af',
    messagingSenderId: '431166589438',
    projectId: 'bmi-1c3db',
    authDomain: 'bmi-1c3db.firebaseapp.com',
    storageBucket: 'bmi-1c3db.firebasestorage.app',
    measurementId: 'G-F99JWSJ1HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-N8zAaFxo7EY6q7qDM4QyRWbyI4YvlDE',
    appId: '1:431166589438:android:af074ddc7881705c4918af',
    messagingSenderId: '431166589438',
    projectId: 'bmi-1c3db',
    storageBucket: 'bmi-1c3db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGSgV1ybjaoZzBe4kfV_kGVebt00cxhGo',
    appId: '1:431166589438:ios:00385daa76adb1674918af',
    messagingSenderId: '431166589438',
    projectId: 'bmi-1c3db',
    storageBucket: 'bmi-1c3db.firebasestorage.app',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGSgV1ybjaoZzBe4kfV_kGVebt00cxhGo',
    appId: '1:431166589438:ios:00385daa76adb1674918af',
    messagingSenderId: '431166589438',
    projectId: 'bmi-1c3db',
    storageBucket: 'bmi-1c3db.firebasestorage.app',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd6I24GWidKNeYlVbHAVJjP6ekjvMlPoo',
    appId: '1:431166589438:web:307b444a6a4994434918af',
    messagingSenderId: '431166589438',
    projectId: 'bmi-1c3db',
    authDomain: 'bmi-1c3db.firebaseapp.com',
    storageBucket: 'bmi-1c3db.firebasestorage.app',
    measurementId: 'G-W5ZSLW2RX2',
  );
}
